<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <!-- dotnet tool packaging -->
        <PackAsTool>true</PackAsTool>
        <ToolCommandName>sm</ToolCommandName>
        <PackageId>Amba.SecretManager</PackageId>

        <Authors>Amba</Authors>
        <Description>CLI tool to manage local secrets (.env files and .secrets directories) across projects</Description>
        <PackageProjectUrl>https://github.com/amba/secret-manager</PackageProjectUrl>
        <PackageLicenseExpression>BSD-2-Clause</PackageLicenseExpression>
        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <ItemGroup>
      <None Include="../../README.md" Pack="true" PackagePath="/" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Spectre.Console" Version="0.54.0" />
      <PackageReference Include="Spectre.Console.Cli" Version="0.53.1" />
      <PackageReference Include="Spectre.Console.Json" Version="0.54.0" />
      <PackageReference Include="Spectre.Console.Testing" Version="0.54.0" />
    </ItemGroup>

</Project>
